---

- name: Docker - Add GPG key.
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"

- name: Docker - Add repository.
  become: yes
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    filename: docker
    state: present
    update_cache: yes

- name: Docker - Install.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Docker - Ensure is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Docker - Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- name: Docker - Ensure docker users are added to the docker group.
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ usuario }}"
  when: usuario | length > 0
